#pragma once

#define AI_SECTION_NAME "AI"

#define ATTACK_INTERVAL_RULE "AttackInterval"
#define BASE_SIZE_ADD_RULE "BaseSizeAdd"
#define POWER_SURPLUS_RULE "PowerSurplus"
#define ATTACK_DELAY_RULE "AttackDelay"
#define POWER_EMERGENCY_FRACTION_RULE "PowerEmergency"
#define HELIPAD_RATIO_RULE "HelipadRatio"
#define HELIPAD_LIMIT_RULE "HelipadLimit"
#define AA_RATIO_RULE "AARatio"
#define AA_LIMIT_RULE "AALimit"
#define DEFENSE_RATIO_RULE "DefenseRatio"
#define DEFENSE_LIMIT_RULE "DefenseLimit"
#define WAR_RATIO_RULE "WarRatio"
#define WAR_LIMIT_RULE "WarLimit"
#define BARRACKS_RATIO_RULE "BarracksRatio"
#define BARRACKS_LIMIT_RULE "BarracksLimit"
#define REFINERY_LIMIT_RULE "RefineryLimit"
#define REFINERY_RATIO_RULE "RefineryRatio"
#define AIRSTRIP_RATIO_RULE "AirstripRatio"
#define AIRSTRIP_LIMIT_RULE "AirstripLimit"
#define INFANTRY_RESERVE_RULE "InfantryReserve"
#define INFANTRY_BASE_MULT_RULE "InfantryBaseMult"
#define PARANOID_RULE "Paranoid"
