#pragma once

#define FIREPOWER_DIFFICULTY_RULE "Firepower"
#define GROUNDSPEED_DIFFICULTY_RULE "GroundSpeed"
#define AIRSPEED_DIFFICULTY_RULE "AirSpeed"
#define ARMOR_DIFFICULTY_RULE "Armor"
#define RATE_OF_FIRE_DIFFICULTY_RULE "RateOfFire"
#define COST_DIFFICULTY_RULE "Cost"
#define REPAIR_DELAY_DIFFICULTY_RULE "RepairDelay"
#define BUILD_DELAY_DIFFICULTY_RULE "BuildDelay"
#define BUILD_SPEED_DIFFICULTY_RULE "BuildSpeed"
#define BUILD_SLOWDOWN_DIFFICULTY_RULE "BuildSlowdown"
