#include <rules_ini_enhancements.h>
#include <RulesIniRuleKey.h>

const RulesIniRuleKey& RALLY_POINTS_RULE_KEY =
	RulesIniRuleKey::BuildRuleKey(ENHANCEMENTS_RULES_SECTION_NAME, RALLY_POINTS_RULE);

const RulesIniRuleKey& A_STAR_PATH_FINDING_RULE_KEY =
	RulesIniRuleKey::BuildRuleKey(ENHANCEMENTS_RULES_SECTION_NAME, A_STAR_PATH_FINDING_RULE);

const RulesIniRuleKey& COMMANDO_GUARD_RULE_KEY =
	RulesIniRuleKey::BuildRuleKey(ENHANCEMENTS_RULES_SECTION_NAME, COMMANDO_GUARD_RULE);

const RulesIniRuleKey& AI_HARVESTERS_PER_REFINERY_RULE_KEY =
	RulesIniRuleKey::BuildRuleKey(ENHANCEMENTS_RULES_SECTION_NAME, AI_HARVESTERS_PER_REFINERY_RULE);

const RulesIniRuleKey& HUMAN_HARVESTERS_PER_REFINERY_RULE_KEY =
	RulesIniRuleKey::BuildRuleKey(ENHANCEMENTS_RULES_SECTION_NAME, HUMAN_HARVESTERS_PER_REFINERY_RULE);

const RulesIniRuleKey& MULTI_WALL_LENGTH_RULE_KEY =
	RulesIniRuleKey::BuildRuleKey(ENHANCEMENTS_RULES_SECTION_NAME, MULTI_WALL_LENGTH_RULE);

const RulesIniRuleKey& FULL_COST_MULTI_WALLS_LENGTH_RULE_KEY =
	RulesIniRuleKey::BuildRuleKey(ENHANCEMENTS_RULES_SECTION_NAME, FULL_COST_MULTI_WALLS_LENGTH_RULE);
