#pragma once

// generic rules - apply to all types
#define IMAGE_RULE "Image"

#define FRIENDLY_NAME_RULE "FriendlyName"

#define BUILD_LEVEL_RULE "BuildLevel"

#define SCENARIO_LEVEL_RULE "ScenarioLevel"

#define PREREQUISITE_RULE "Prerequisite"

#define COST_RULE "Cost"

#define BUILDABLE_RULE "Buildable"

#define FLAMMABLE_RULE "Flammable"

#define SPEED_RULE "Speed"

#define STRENGTH_RULE "Strength"

#define HOUSES_RULE "Houses"

#define OWNER_RULE "Owner"

#define PRIMARY_WEAPON_RULE "PrimaryWeapon"

#define SECONDARY_WEAPON_RULE "SecondaryWeapon"

#define ARMOR_RULE "Armor"

#define AMMO_RULE "Ammo"

#define SIGHT_RANGE_RULE "SightRange"

#define REWARD_RULE "Reward"

#define DETECT_CLOAKED_OBJECTS_RULE "DetectCloakedObjects"

#define CRUSHABLE_RULE "Crushable"

#define LEADER_RULE "Leader"

#define TWO_SHOOTER_RULE "TwoShooter"

#define HAS_THEATER_GFX_RULE "HasTheaterSpecificGraphic"

#define SHOW_NAME_RULE "ShowName"

#define IS_MOD_TYPE_RULE "IsModType"

// shared non-infantry rules
#define HAS_CREW_RULE "HasCrew"

#define TURRET_EQUIPPED_RULE "TurretEquipped"

#define REPAIRABLE_RULE "Repairable"

// shared infantry/unit rules
#define EXPLODES_UPON_DEATH_RULE "ExplodesUponDeath"

#define DEATH_EXPLOSION_ANIMATION_RULE "DeathExplosionAnimation"

#define DEATH_EXPLOSION_WARHEAD_RULE "DeathExplosionWarhead"

#define DEATH_EXPLOSION_DAMAGE_RULE "DeathExplosionDamage"

// shared unit/aircraft rules
#define RATE_OF_TURN_RULE "RateOfTurn"

#define TRANSPORTER_RULE "CanTransportInfantry"

#define TRANSPORT_CAPACITY_RULE "TransportCapacity"

#define DEFAULT_TRANSPORT_CAPACITY 5u
