#pragma once

#define BULLET_HIGH_RULE "High"

#define BULLET_ANTI_AIRCRAFT_RULE "AntiAircraft"

#define BULLET_TRANSLUCENT_RULE "Translucent"

#define BULLET_ARCING_RULE "Arcing"

#define BULLET_HOMING_RULE "Homing"

#define BULLET_DROPPING_RULE "Dropping"

#define BULLET_INVISIBLE_RULE "Invisible"

#define BULLET_PROXIMITY_ARMED_RULE "ProximityArmed"

#define BULLET_FLAME_EQUIPPED_RULE "FlameEquipped"

#define BULLET_FUELED_RULE "Fueled"

#define BULLET_FACELESS_RULE "Faceless"

#define BULLET_INACCURATE_RULE "Inaccurate"

#define BULLET_WARHEAD_RULE "Warhead"

#define BULLET_ARMING_RULE "Arming"

#define BULLET_RANGE_RULE "Range"
