#include <RulesIniRuleKey.h>

#include "rules_ini_game.h"
#include "tiberian_dawn_mods.h"

const RulesIniRuleKey& AIRCRAFT_COUNT_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(MOD_RULES_SECTION_NAME, AIRCRAFT_COUNT_RULE);

const RulesIniRuleKey& BUILDING_COUNT_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(MOD_RULES_SECTION_NAME, BUILDING_COUNT_RULE);

const RulesIniRuleKey& BULLET_COUNT_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(MOD_RULES_SECTION_NAME, BULLET_COUNT_RULE);

const RulesIniRuleKey& INFANTRY_COUNT_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(MOD_RULES_SECTION_NAME, INFANTRY_COUNT_RULE);

const RulesIniRuleKey& UNIT_COUNT_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(MOD_RULES_SECTION_NAME, UNIT_COUNT_RULE);

const RulesIniRuleKey& WARHEAD_COUNT_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(MOD_RULES_SECTION_NAME, WARHEAD_COUNT_RULE);

const RulesIniRuleKey& WEAPON_COUNT_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(MOD_RULES_SECTION_NAME, WEAPON_COUNT_RULE);


const RulesIniRuleKey& MAX_BUILD_DISTANCE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, MAX_BUILD_DISTANCE_RULE);


const RulesIniRuleKey& TIBERIUM_BLOSSOM_TREE_DAMAGE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TIBERIUM_BLOSSOM_TREE_DAMAGE_RULE);


const RulesIniRuleKey& CREDITS_PER_TIBERIUM_SCOOP_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, CREDITS_PER_TIBERIUM_SCOOP_RULE);

const RulesIniRuleKey& MAX_HARVESTER_CAPACITY_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, MAX_HARVESTER_CAPACITY_RULE);


const RulesIniRuleKey& PRODUCTION_STEPS_PER_TICK_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, PRODUCTION_STEPS_PER_TICK_RULE);

const RulesIniRuleKey& FACTORY_COUNT_STEP_MULTIPLER_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, FACTORY_COUNT_STEP_MULTIPLER_RULE);

const RulesIniRuleKey& TOTAL_PRODUCTION_STEPS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TOTAL_PRODUCTION_STEPS_RULE);


const RulesIniRuleKey& UNIT_REPAIR_FACTOR_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, UNIT_REPAIR_FACTOR_RULE);

const RulesIniRuleKey& UNIT_REPAIR_STEP_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, UNIT_REPAIR_STEP_RULE);


const RulesIniRuleKey& AIRCRAFT_REPAIR_FACTOR_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, AIRCRAFT_REPAIR_FACTOR_RULE);

const RulesIniRuleKey& AIRCRAFT_REPAIR_STEP_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, AIRCRAFT_REPAIR_STEP_RULE);


const RulesIniRuleKey& RENAME_TECH_CENTER_TO_PRISON_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, RENAME_TECH_CENTER_TO_PRISON_RULE);

const RulesIniRuleKey& SURVIVORS_FROM_BUILDINGS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, SURVIVORS_FROM_BUILDINGS_RULE);

const RulesIniRuleKey& ALLOW_BUILDING_BESIDE_WALLS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, ALLOW_BUILDING_BESIDE_WALLS_RULE);

const RulesIniRuleKey& PREVENT_BUILDING_IN_SHROUD_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, PREVENT_BUILDING_IN_SHROUD_RULE);

const RulesIniRuleKey& HIDE_E3_FROM_GDI_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_E3_FROM_GDI_RULE);

const RulesIniRuleKey& HIDE_MSAM_FROM_GDI_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_MSAM_FROM_GDI_RULE);

const RulesIniRuleKey& HIDE_APC_FROM_NOD_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_APC_FROM_NOD_RULE);

const RulesIniRuleKey& HIDE_TMPL_FROM_GDI_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_TMPL_FROM_GDI_RULE);

const RulesIniRuleKey& HIDE_OBLI_FROM_GDI_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_OBLI_FROM_GDI_RULE);

const RulesIniRuleKey& HIDE_MSAM_FROM_NOD_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_MSAM_FROM_NOD_RULE);

const RulesIniRuleKey& HIDE_ADV_COMM_FROM_NOD_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_ADV_COMM_FROM_NOD_RULE);

const RulesIniRuleKey& ALLOW_NOD_TO_BUILD_NUK2_EARLY_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, ALLOW_NOD_TO_BUILD_NUK2_EARLY_RULE);

const RulesIniRuleKey& HIDE_HELIPAD_FROM_NOD_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_HELIPAD_FROM_NOD_RULE);

const RulesIniRuleKey& HIDE_SBAG_FROM_GDI_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, HIDE_SBAG_FROM_GDI_RULE);

const RulesIniRuleKey& SET_GDI_SCENARIO_2_BUILD_LEVEL_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, SET_GDI_SCENARIO_2_BUILD_LEVEL_RULE);

const RulesIniRuleKey& ALLOW_BUILDING_ALL_FOR_HOUSE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, ALLOW_BUILDING_ALL_FOR_HOUSE_RULE);

const RulesIniRuleKey& ONLY_GDI_CAN_USE_ION_CANNON_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, ONLY_GDI_CAN_USE_ION_CANNON_RULE);

const RulesIniRuleKey& ONE_TIME_NUKE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, ONE_TIME_NUKE_RULE);

const RulesIniRuleKey& ONLY_ALLOW_NUKE_IF_PARTS_COLLECTED_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, ONLY_ALLOW_NUKE_IF_PARTS_COLLECTED_RULE);

const RulesIniRuleKey& TIBERIUM_INFANTRY_DAMAGE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TIBERIUM_INFANTRY_DAMAGE_RULE);

const RulesIniRuleKey& TIBERIUM_GROWTH_RATE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TIBERIUM_GROWTH_RATE_RULE);

const RulesIniRuleKey& TIBERIUM_SPREAD_RATE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TIBERIUM_SPREAD_RATE_RULE);

const RulesIniRuleKey& SPEEDY_BUILDS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, SPEEDY_BUILDS_RULE);

const RulesIniRuleKey& ATTACKER_ADVANTAGE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, ATTACKER_ADVANTAGE_RULE);

const RulesIniRuleKey& SMART_DEFENCE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, SMART_DEFENCE_RULE);

const RulesIniRuleKey& TARGET_TREES_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TARGET_TREES_RULE);

const RulesIniRuleKey& MCV_REDEPLOY_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, MCV_REDEPLOY_RULE);

const RulesIniRuleKey& VISCEROIDS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, VISCEROIDS_RULE);

const RulesIniRuleKey& UNITS_INDESTRUCTIBLE_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, UNITS_INDESTRUCTIBLE_RULE);

const RulesIniRuleKey& THREE_POINT_TURNS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, THREE_POINT_TURNS_RULE);

const RulesIniRuleKey& TIBERIUM_GROWS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TIBERIUM_GROWS_RULE);

const RulesIniRuleKey& TIBERIUM_SPREADS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, TIBERIUM_SPREADS_RULE);

const RulesIniRuleKey& SLOW_TIBERIUM_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, SLOW_TIBERIUM_RULE);

const RulesIniRuleKey& SHOW_BIBS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, SHOW_BIBS_RULE);

const RulesIniRuleKey& AUTO_SCATTER_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, AUTO_SCATTER_RULE);

const RulesIniRuleKey& NAME_CIVILIAN_BUILDINGS_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, NAME_CIVILIAN_BUILDINGS_RULE);

const RulesIniRuleKey& CAN_BUY_HELIPAD_ONLY_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, CAN_BUY_HELIPAD_ONLY_RULE);

const RulesIniRuleKey& DEBUG_LOGGING_RULE_KEY =
    RulesIniRuleKey::BuildRuleKey(GAME_RULES_SECTION_NAME, DEBUG_LOGGING_RULE);
