#pragma once

// building rules
#define BIBBED_RULE "Bibbed"

#define WALL_RULE "Wall"

#define FACTORY_RULE "Factory"

#define SIMPLE_DAMAGE_RULE "SimpleDamage"

#define STURDY_RULE "Sturdy"

#define CAPTUREABLE_RULE "Captureable"

#define FIXED_SPEED_ANIMATION_RULE "FixedSpeedAnimation"

#define UNSELLABLE_RULE "Unsellable"

#define FACTORY_TYPE_RULE "FactoryType"

#define STORAGE_CAPACITY_RULE "StorageCapacity"

#define POWER_OUTPUT_RULE "PowerOutput"

#define POWER_INPUT_RULE "PowerInput"
