#pragma once

// unit rules
#define CAN_BE_FOUND_IN_CRATE_RULE "CanBeFoundInCrate"

#define LIMITED_FACINGS_RULE "LimitedFacings"

#define CAN_CRUSH_INFANTRY_RULE "CanCrushInfantry"

#define CAN_HARVEST_RULE "CanHarvest"

#define RADAR_EQUIPPED_RULE "RadarEquipped"

#define HAS_FIRE_ANIMATION_RULE "HasFireAnimation"

#define LOCK_TURRET_RULE "LockTurret"

#define HAS_TRACKS_RULE "HasTracks"

#define HUGE_RULE "Huge"

#define CAN_CLOAK_RULE "CanCloak"

#define CONSTANT_ANIMATION_RULE "ConstantAnimation"

#define UNIT_SPEED_RULE "UnitSpeed"

#define SELF_REPAIR_RULE "SelfRepair"
