name: Build & Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-2016
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        shell: powershell
        run: |
          $vsPath = vswhere -latest `
            -prerelease `
            -products * `
            -requires Microsoft.Component.MSBuild `
            -property installationPath

          if (!$vsPath) {
            throw "Failed to find Visual Studio"
          }

          $msBuildPath = join-path $vsPath "MSBuild\Current\Bin"

          if (!(test-path $msBuildPath)) {
            $msBuildPath = join-path $vsPath "MSBuild\15.0\Bin"

            if (!(test-path $msBuildPath)) {
              throw "Failed to find MSBuild"
            }
          }

          Write-Host "::set-env name=VS_PATH::${vsPath}"
          Write-Host "::set-env name=MSBUILD_PATH::${msBuildPath}"

          Write-Host "::add-path::${msBuildPath}"

      - name: Build Tiberian Dawn Test App
        run: scripts\build-test.bat
        env:
          CL: /DCI_ENV

      - name: Run Test App
        working-directory: bin\Win32 
        run: .\TiberianDawn.exe

      - name: Package for Steam Workshop
        run: scripts\build-and-package.bat

      - name: Read Short Git Commit Hash
        shell: powershell
        run: |
          $gitCommit = $env:GITHUB_SHA.substring(0, 7)

          Write-Host "::set-env name=GIT_COMMIT::${gitCommit}"

      - uses: actions/upload-artifact@v2
        with:
          name: steam-workshop-mod
          path: .steam-workshop\cnc-td-nco-mod-steam-${{ env.GIT_COMMIT }}.zip

      - uses: actions/upload-artifact@v2
        with:
          name: manual-install-mod
          path: .steam-workshop\cnc-td-nco-mod-${{ env.GIT_COMMIT }}.zip
